# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Igs < Formula
  desc "Minimal interactive git status"
  homepage "https://github.com/leohenon/interactive-git-status"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leohenon/interactive-git-status/releases/download/v0.2.1/igs_darwin_amd64.tar.gz"
      sha256 "f695462e42e9355eb9fd883447ba2b3eefb295008884f7ceb39516a80e13c308"

      define_method(:install) do
        bin.install "igs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leohenon/interactive-git-status/releases/download/v0.2.1/igs_darwin_arm64.tar.gz"
      sha256 "cd1912981c68614937fec52075efb5d729c8643fd097c145ae232a8c60ebb57f"

      define_method(:install) do
        bin.install "igs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/leohenon/interactive-git-status/releases/download/v0.2.1/igs_linux_amd64.tar.gz"
      sha256 "b11c66e5c58a3276a73440b1634ab058d08c5c68e73750e9f063957b21babf05"
      define_method(:install) do
        bin.install "igs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/leohenon/interactive-git-status/releases/download/v0.2.1/igs_linux_arm64.tar.gz"
      sha256 "4103e655bc91831829a80b8a788edb5ba63d15b16f3123092108139115ab0b41"
      define_method(:install) do
        bin.install "igs"
      end
    end
  end

  test do
    system "#{bin}/igs", "--help"
  end
end
