# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Igs < Formula
  desc "Minimal interactive git status"
  homepage "https://github.com/leohenon/interactive-git-status"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leohenon/interactive-git-status/releases/download/v0.1.0/igs_darwin_amd64.tar.gz"
      sha256 "fc9d8c259b683a21b8109bea8702c1524bab02baee40f6e0925e5f56a3a3993f"

      define_method(:install) do
        bin.install "igs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leohenon/interactive-git-status/releases/download/v0.1.0/igs_darwin_arm64.tar.gz"
      sha256 "331f728ac85776518ee0bb9d77f8168b8a35ad370087bd08d17b0422eafc95ea"

      define_method(:install) do
        bin.install "igs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/leohenon/interactive-git-status/releases/download/v0.1.0/igs_linux_amd64.tar.gz"
      sha256 "ab445db4d1828b1f374f55140575e23b7a967c0a8b36fd5d7d91902fa6825275"
      define_method(:install) do
        bin.install "igs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/leohenon/interactive-git-status/releases/download/v0.1.0/igs_linux_arm64.tar.gz"
      sha256 "53b94742e51e4eb14e9855292973bd655c154977c104b77c690886b71833b9aa"
      define_method(:install) do
        bin.install "igs"
      end
    end
  end

  test do
    system "#{bin}/igs", "--help"
  end
end
