# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Igs < Formula
  desc "Minimal interactive git status"
  homepage "https://github.com/leohenon/interactive-git-status"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leohenon/interactive-git-status/releases/download/v0.1.2/igs_darwin_amd64.tar.gz"
      sha256 "6496b7c5b8f1f5caa1e4cabc4ac5f90ffb5d73ca4a7d7b41340a2beba45543ca"

      define_method(:install) do
        bin.install "igs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leohenon/interactive-git-status/releases/download/v0.1.2/igs_darwin_arm64.tar.gz"
      sha256 "0fa6bb8ff8e9d2dbc19ec7305d781d50ae7e49ae0c7087c7eac44578a09a08ce"

      define_method(:install) do
        bin.install "igs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/leohenon/interactive-git-status/releases/download/v0.1.2/igs_linux_amd64.tar.gz"
      sha256 "5c704dd461aaf0eed18c033b3dc35706ff14ae28518a4f2bc5739f37dd6b91dd"
      define_method(:install) do
        bin.install "igs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/leohenon/interactive-git-status/releases/download/v0.1.2/igs_linux_arm64.tar.gz"
      sha256 "69b766586ad4f4bce5ad5ac0051a2e7e48fe2520a872697d0bb77f1324e9b261"
      define_method(:install) do
        bin.install "igs"
      end
    end
  end

  test do
    system "#{bin}/igs", "--help"
  end
end
